### ISSUE TITLE
🐛 iOS | The shape of Achievements at the bottom of the screen is distorted

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#455] opened 2023-10-03 02:43 UTC
**Steps** to reproduce:
1. Go to the Leaderboard tab
2. Open Profile popup by tapping on any item in the list

**Expected result:**
If Achievements do not fit on the screen they should be "cropped" by the screen.

**Actual result:**
The shape of the Achievements in the last row is distorted (see the screenshot below).

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/9caf87b8-553a-4fc8-bba9-c71cfe2b0d2e" width=300 />

**Comment by AntPolkanov** [comment] 2023-10-03 02:49
Similar to https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/445

**Comment by matt-goldman** [comment] 2023-10-04 04:29
@Anton-Polkanov looks like a duplicate of #445 to me - do we need both issues?

**Comment by matt-goldman** [comment] 2023-10-04 04:32
Cannot replicate this with the current alpha build. I suspect this is also related to https://github.com/dotnet/maui/issues/17817. Does not occur with the workaround in place.

**Comment by AntPolkanov** [comment] 2023-10-05 00:06
@matt-goldman , cannot reproduce it on v2.2.1(6) too.

**Closed** 2023-10-05 03:17 UTC
Labels: bug, blocked
