### ISSUE TITLE
:bug: App crashes on leaderboard when tapping "All time"

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#424] opened 2023-06-23 05:08 UTC
cc: @sethdailyssw

**Comment by AntPolkanov** [comment] 2023-08-03 23:29
Talked to @sethdailyssw, played with it myself - cannot reproduce the issue. 
Closing for now.
Will keep an eye on when we release MAUI version.

**Closed** 2023-08-08 02:29 UTC
Labels: bug
