### ISSUE TITLE
UI - button text needs more contrast

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Rewards.Mobile#399] opened 2022-10-02 23:13 UTC
When I was trying to get points for subscribing to the YouTube channel - the modal initially looked broken as I did not notice the "save" text in the button.

![image](https://user-images.githubusercontent.com/600044/193480517-22cc2d49-1aee-4b16-8478-e45dbb6b53c3.png)

**Comment by matt-goldman** [comment] 2022-10-04 22:14
From @wicksipedia:
Hey Matt G

>	1. Do you still think this UX is problematic?

Yes, the button looks like it is in an enabled state but I can’t see text – so it looks like a buggy UI.

I’d recommend fading the button background color instead of the text color – like what bootstrap does https://getbootstrap.com/docs/4.1/components/buttons/#disabled-state 

>	2. Do you think this needs a better cue? Like an X in the top right corner for example?

That or a cancel button

FYI I think this conversation should be on the GitHub issue


From @matt-goldman

Hi Matt W
cc: @jaydenalchin 
Thanks for testing!

> UI - button text needs more contrast · Issue #399 · SSWConsulting/SSW.Rewards (github.com)
The button is disabled until you enter some text, this is expected until you’ve put your username in. I can confirm from the video you attached to your other issue that this is working as expected.

1.	Do you still think this UX is problematic?

If you don’t want to enter something, or enter something and don’t want to save it, you can dismiss the dialog by tapping behind it.

2.	Do you think this needs a better cue? Like an X in the top right corner for example?

**Comment by AntPolkanov** [comment] 2024-04-13 11:53
Not relevant in v2024, closing.

**Closed by AntPolkanov** 2024-04-13 11:53 UTC
Labels: mobile
