### ISSUE TITLE
💄 Mobile | Settings Page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#835] opened 2024-04-11 03:52 UTC
Pain:
Our Flyout is starting to get very cluttered, we should move items into a Settings page as per Joe's design.

- [ ] Add a Settings page to the Flyout
- [ ] Move User Delete Profile button
- [ ] Move Intro button

**Comment by AntPolkanov** [comment] 2024-04-14 22:53
Duplicate of #582.
Closing this one.

**Closed by AntPolkanov** 2024-04-14 22:53 UTC
