### ISSUE TITLE
Give-away registration

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#377] opened 2022-08-01 23:52 UTC
@william-liebenberg @wicksipedia @matt-goldman @lukecookssw @adamcogan 

As per our conversation, we want users to register for in-person giveaways at events. Users will scan a QR code to enter into the pool, and our Admin users will have the Portal randomly select a winner.

## Acceptance Criteria
- [x] Mobile App can scan event-specific giveaway QR codes (e.g. "NDC Sydney day 1 giveaway")
- [x] Each user may only scan the QR code once
- [x] Admin Portal shows a list of registered users per giveaway

## Gold Plating
- [x] Admin Portal can randomly select a user from the registered users pool
- [ ] A winner is confirmed in the Portal by Admin Users, preventing them from being chosen again (in the event that there are multiple giveaway draws)

**Comment by matt-goldman** [comment] 2024-01-02 05:31
Closing as duplicate of completed work: https://github.com/SSWConsulting/SSW.Rewards.API/pull/76

**Closed by matt-goldman** 2024-01-02 05:31 UTC
